#!/usr/bin/env php
<?php

define('DS', DIRECTORY_SEPARATOR);
define('FILE_PATH_ROOT', __DIR__ . DS);
define('FILE_PATH_ROOT_WEB', FILE_PATH_ROOT . 'web' . DS);
define('FILE_PATH_VENDOR', FILE_PATH_ROOT . 'vendor' . DS);

// folder for config
$env = 'test';
$env = file_exists(FILE_PATH_ROOT . '.dev') ? 'dev' : $env;
$env = file_exists(FILE_PATH_ROOT . '.prod') ? 'prod' : $env;
defined('YII_ENV') or define('YII_ENV', $env);

// debug mode
$debug = ($env == 'test' || $env == 'dev') ? true : false;
defined('YII_DEBUG') or define('YII_DEBUG', $debug);

define('FILE_PATH_CONFIG', FILE_PATH_ROOT . 'config' . DS);
define('FILE_PATH_CONFIG_ENV', FILE_PATH_CONFIG . $env . DS);

require(FILE_PATH_VENDOR . 'autoload.php');
require(FILE_PATH_VENDOR . 'yiisoft' . DS . 'yii2' . DS . 'Yii.php');

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

$config = require(FILE_PATH_CONFIG_ENV . 'main_console.php');

$app = new yii\console\Application($config);
$exitCode = $app->run();

exit($exitCode);